### ISSUE TITLE
Overlap-kuvan tooltip puuttuu

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#10]
@nomasi: Selitetään sanallisesti sopivuus

**Comment by tjjalava** [comment]
Tekstit tähän?

**Comment by nomasi** [comment]
Tää on sama kuin siellä vanhassa detailed view -ikkunassa sen overlap-kuvan yhteydessä (tooltip).  
sizeme-ui.js:2041 alkaen $tip_txts -muuttuja.  Tossa vanhassa ne on vähän kömpelösti kerätty samaan aikaan kuin niitä kuvia tehtiin, joten kantsii varmaan tehdä erikseen.

**Comment by nomasi** [comment]
![image](https://cloud.githubusercontent.com/assets/6150822/25815999/585995de-342b-11e7-91eb-f6cde3f4f22d.png)

**Comment by tjjalava** [comment]
Fixed in 13b64e6
