### ISSUE TITLE
Slider barin indikaattori voisi olla myös svg

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#12]

**Comment by nomasi** [comment]
Itse slider bariin on tulossa aika erilainen ulkoasu default-valinnaksi.  Mä speksaan ja testataan demossa.

**Comment by nomasi** [comment]
[sizeme_slider_indicators_in_svg.zip](https://github.com/BA-Group/sizeme-react/files/959881/sizeme_slider_indicators_in_svg.zip)

**Comment by nomasi** [comment]
Paitsi et just muistin et ei siinä uudessa ja "paremmassa" fashion-sliderissa ei ole tota samaa indikaattoria ollenkaan vaan kolmio.  Teen senkin.

**Comment by nomasi** [comment]
[sizeme_slider_bg_and_indicators_in_svg_2017-05-04.zip](https://github.com/BA-Group/sizeme-react/files/976500/sizeme_slider_bg_and_indicators_in_svg_2017-05-04.zip)

**Comment by nomasi** [comment]
Ohessa svg:nä fit_indicator (red triangle), fit_recommendation_indicator (gray hollow triangle) ja uusi grid-tausta, joka tulee koko table.slider_table:n taustakuvaksi.  Tyyli tälle voisi olla:

background-image: url(slider_bg_black_grid.svg);
background-position: bottom center;
background-size: cover;
background-repeat: no-repeat;

**Comment by nomasi** [comment]
Pitää varmaan säätää vielä korkeuksia ym.  Myös näiden liikkuvien indicatoreiden kohdistaminen oli ainakin mulle aina vähän hankalaa että saa ne osumaan keskelle.  En osaa sanoa onko se helpompaa vai vaikeampaa svg:n kanssa.

**Comment by nomasi** [comment]
Koko tablen peittävä taustakuva on mahdollinen vasta kun issuen #26 myötä kaikki viisi aluetta on samankokoisia.  (yritin myös tehdä jokaiselle td:lle oman vastaavan taustakuvan, mutta sen hallinta oli huomattavasti vaikeampaa.  erityisesti viivan paksuudet reunoilla.)
