### ISSUE TITLE
Nyt defaultina näkyy se slider_area; aikaisemmin vain detailed viewssä

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#13]
@nomasi: Olisko nyt ton paikka auringossa?

**Comment by nomasi** [comment]
Tähän ei ole suuri yleisö vieläkään lämmennyt.  Piilotetaan slider_area tuotesivulla mut pidetään näkyvissä detailed viewssa.  Kuten nyt.  

Roban Masalla oli tähän lisääkin ajatuksia mut hahmotellaan niitä myöhemmin.
