### ISSUE TITLE
Cog-nappi: Login/signup to SizeMe; defaultina login

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#15]
Avautuvan ponnahdusikkunan default voisi olla sign up; toisarvoisena login

**Comment by tjjalava** [comment]
@nomasi: Defaulttina login vai sign up?

**Comment by nomasi** [comment]
Tähän tulee vähän muutoksia tän päivän hahmotteluiden seurauksena.  Jaakko tekee yhden mockupin ja mä voin speksata.

**Comment by nomasi** [comment]
Korvautuu issuella #25
