### ISSUE TITLE
Cog-nappi: Login/signup to SizeMe -ulkoasu?

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#17]

**Comment by nomasi** [comment]
Mikäli käyttäjä ei ole kirjautunut, poistetaan cog-nappi kokonaan.  Issue #25 korvaa tän.

**Comment by nomasi** [comment]
Kirjautuneille käyttäjille cog-nappi edelleen avaa profiililistan.

**Comment by tjjalava** [comment]
#25 suljettu, joten tää kunnossa
