### ISSUE TITLE
Z-index-ongelmia modal-ikkunoissa: mittavideot, size guide tms.

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#18]

**Comment by tjjalava** [comment]
@nomasi: En saa toistumaan missään. Voihan niitä z-index-arvoja nostaa kautta linjan, mutta mikä olisi sopiva luku?

**Comment by nomasi** [comment]
Tää on vähän hankala kun moni magento-plugari kirjoittelee ihan omiaan vaikka siihen tuotekuvazoomiin, niissä voi olla z-indeksit oikeastaan mitä vaan, mut niitä voi sitten kauppakohtaisesti kohennella kyllä.  

Laitetaan lähtökohtaisesti z-index: 100;

**Comment by tjjalava** [comment]
ne z-indexit on jo nyt 1000, ja siinä cog-menussa taitaa olla 2000 ;)

**Comment by tjjalava** [comment]
En saa tätä toistumaan missään. Onko tarkempia speksejä vai suljetaanko?

**Comment by nomasi** [comment]
![image](https://cloud.githubusercontent.com/assets/6150822/25815480/3c131a46-3429-11e7-8c4f-7e9476a31a5b.png)

**Comment by nomasi** [comment]
![image](https://cloud.githubusercontent.com/assets/6150822/25815658/2092b82a-342a-11e7-9f08-01ee8dd9150e.png)

**Comment by nomasi** [comment]
![image](https://cloud.githubusercontent.com/assets/6150822/25815666/2b6ef0d8-342a-11e7-8aa7-b565a6559ff9.png)

**Comment by nomasi** [comment]
.measurement-guide-overlay { z-index: 10; } 
näyttäisi riittävän
