### ISSUE TITLE
Tooltipit selittämään mikä toi slider on.  

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#21]

**Comment by nomasi** [comment]
Ei avata suoraan pyytämättä.  Mutta klikatessa sliderin indicatoria aukeaa tooltip jossa teksti "This indicates your fit for the selected size."

**Comment by nomasi** [comment]
Tehdään sekä FitIndicatoriin ja RecommendationIndicatoriin hover-aktivoituvat tooltipit.  Tekstit alustavasti: 

FitIndicator: "This indicates how size %s will fit you."
RecommendationIndicator: "We recommend that your fit is around this area."

**Comment by tjjalava** [comment]
@nomasi, käännökset vielä

**Comment by tjjalava** [comment]
Valmis PR #54 myötä
