### ISSUE TITLE
Miten profiilia pääsee editoimaan?

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#23]
@nomasi: Linkki SizeMe-profiilisivulle.  Pitäiskö avautua uuteen ikkunaan?  Toiminta jos editoi ei oo dynaaminen kuitenkaan?

**Comment by tjjalava** [comment]
Pääsivun input-kenttiin olisi tarkoitus ladata profiilimitat ja niiden muutokset pitäisi pystyä tallentamaan valittuun profiiliin. Aattelin, että tulisko sitten size-guide-modaaliin myös input-kentät kaikille kyseisen itemin mitoille, jonka kautta niitä voisi muutella. Sitten ei tarttis lainkaan mennä sizeme.com:iin missään vaiheessa

**Comment by nomasi** [comment]
Joo, jossain määrin näin.  Ja hyvä että sinne size guide/detailed view:hin tulee ne kaikki tuotteen inputit, vaikka niistä tärkeimmät onkin siinä tuotesivulla.  

Mut, mä muuttaisin silti sen profiilinvaihto-menun niin että selectin sijasta siinä on lista accountin profiileista ja jokaisen rivin perässä pieni kynä-ikoni josta pääsee editoimaan tarvittaessa.  Samalla sen listan viimeiseksi voisi lisätä "Add new profile"-rivin, koska sitä toiminnallisuutta (vaikkakin varmaan vähän harvinaisempi normikäytössä) ei ole tuolla tuotesivulla olemassa vissiin missään muodossa.  Mä voin pyytää Jaakolta speksin et miltä tällainen profiilinvaihtomenu näyttäisi.

**Comment by tjjalava** [comment]
Tarkoittaako editointi tässä ohjausta sizeme.comiin vai lähinnä profiilinimen/sukupuolen muokkausta?

**Comment by nomasi** [comment]
Ohjausta sizeme.comiin.

**Comment by tjjalava** [comment]
Onko jaakon spekseistä tietoa?

**Comment by nomasi** [comment]
Mockup tilattu Jaakolta.

**Comment by nomasi** [comment]
![sizeme_profileselection_0517](https://cloud.githubusercontent.com/assets/6150822/25994796/03155316-3718-11e7-9100-13979b30fadb.jpg)

**Comment by nomasi** [comment]
Tällä oheisella speksillä voidaan mennä.  Voidaan hieroa noi tyylit julkaisukuntoon sit ihan lopuksi.
