### ISSUE TITLE
Lisätään signup-mahdollisuus tuotesivulle omaan laatikkoonsa

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#27]
![sizeme_2g_0517_v2b](https://cloud.githubusercontent.com/assets/6150822/25709839/241363ee-30f3-11e7-932f-645f3d08418a.jpg)

**Comment by nomasi** [comment]
Ei-kirjautuneille käyttäjille: kun yksikin mitta on syötetty, kirjoitetaan SizeMe-sisällön alareunaan oheinen boksi jota kautta voi luoda SizeMe-tilin ja siihen yhden profiilin oheisilla mitoilla.

**Comment by nomasi** [comment]
Default-teksti: "Save your measurements, so you don't have to remember them ever again.".  Tän voi retailer overridata kaupassa (koska saattaa haluta mainostaa jotain alennusta), joten tästä kirjoitetaan joku versio varmaan UI-optionseihin?

**Comment by nomasi** [comment]
Toi boksi on sen verran iso että siihen olisi varmaan hyvä tehdä oikeaan reunaan ruksi josta sen saa piiloon ja sen tilalle tulisi teksti "Save these measurements" samaan tyyliin kuin issuen #25 -linkki.  Save these measurementsin painaminen voisi taas kirjoittaa tän saman boksin uudestaan.  Vähän kyseenalainen ja tästä kysytään mielipiteitä testeissä.

**Comment by tjjalava** [comment]
Huh, tilin ja profiilin luonti suoraan sivulta olikin työläämpää kuin osasin odottaa. Jotain pikkuviilauksia voi olla vielä jäljellä, en sulje vielä, jotta muistan tehdä ne
