### ISSUE TITLE
Lisätään invokeElement ja invokeEvent

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#30]
Otetaan käyttöön uiOptionsin invokeElement ja invokeEvent myös koodissa.

**Comment by nomasi** [comment]
Testikeissi:

https://www.sizemedemo.com/magento19/shirts/t-shirt-db.html?___store=rwd

**Comment by tjjalava** [comment]
Päädyin nyt siihen, että näitä kokovalintasysteemejä tehdään eksplisiittisesti per toteutus, ainakin nyt toistaiseksi. Eli nyt on valmiina magenton perus-alasvetovalikko sekä swatches-toteutus. UiOptionseissa ei tarvita invokeEvent-optioa ollenkaan, mutta invokeElement on vielä. Sen lisäksi tulee uusi optio `sizeSelectorType`, jolle voi nyt antaa arvona _default_ ja _swatches_.

Kommitti seuraa kohta

**Comment by tjjalava** [comment]
Korjattu: https://github.com/BA-Group/sizeme-react/commit/6f20fef4d70363bc9132dcbadf53f43311f9b1a1

**Comment by nomasi** [comment]
Tähän pitää tehdä erikoiskeissi Kookengälle.  Heillä swatches on toteutettu niin että klikattavan elementin id on eri rakenteella kuin Magentossa normaalisti.  

Tehdään siis "swatches-koo", jossa seurattavan li-elementin id on tyyliin "li-15-1", ja tässä tuo 15 on se seurattava size-attribute-id (magenton vakio olisi tässä "option15").

**Comment by tjjalava** [comment]
joo, näköjään toi ei taida edes olla mikään virallinen "swatches"-toteutus vaan joku rip-off.

**Comment by nomasi** [comment]
juu, taitaa olla ihan itse veistossa tehty.  toi swatches-systeemi tuli magentoon vasta tosi myöhään, joten näitä erilaisia virityksiä on varmaan maailma pullollaan (vrt. Makian joku buttonize-hässäkkä).
