### ISSUE TITLE
Sizing bar placeholder

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#33]
Lisätään sizeme_slider elementtiin placeholder-teksti "Enter your measurements to find the right size." jos mittoja ei ole vielä yhtään paikoillaan.  Placeholder tehdään sliderin päälle samanlevyisenä (taustaväri vaikka vähän läpinäkyvä) ja se saa feidata piiloon kun yksikin mitta on sisällä.  

Oikeastaan pelkkä lisäluokka sizeme_slideriin (ja sen placeholderin kirjoitus) riittää tähän.  Saattaa nimittäin olla että ne sliderin tekstit (Too small, Slim jne) piilotetaan kokonaan kun placeholder on näkyvissä tms.

**Comment by tjjalava** [comment]
@nomasi tästä ei tullut kovin nättiä mun mielestä. Kannattaa kattoa pitäiskö sitä vähän stailata enemmän..

**Comment by nomasi** [comment]
Tarpeeksi lähellä on.  Me katotaan Jaakon kanssa tämäkin läpi.  Hyvä!
