### ISSUE TITLE
Input: Mittojen päivittyminen aktiiviseen profiiliin ei toimi

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#39]
Kun joku profiili on aktiivinen, tulisi mittaa päivittämällä myös profiilin ks. mitta päivittyä, eikös?

**Comment by tjjalava** [comment]
tää oli vähän auki. Siis joo, pitäis päivittyä, mutta päivitetäänkö automaattisesti vai onko erikseen joku save-nappula?

**Comment by nomasi** [comment]
Mun mielestä voidaan päivittää automaattisesti.  Se on jotenkin kuitenkin oletettavaa.
