### ISSUE TITLE
Lisätään fitVerdict-kenttä OverlapBoxiin

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#43]
Kirjoitetaan fitVerdict-string kolmanneksi elementiksi OverlapBoxiin.  Saa olla defaultina display: none;.  

Liittyy Phix Clothing UK:n UI-tuunauksiin.

**Comment by tjjalava** [comment]
samalle tasolle kuin .overlap-svg ja .overlap-text? Onko sisäinen rakenne sama kuin .overlap-textillä (siellä sisällä on vielä toinen div)

**Comment by nomasi** [comment]
Samalle tasolle juu ja voi olla sama sisäinen rakenne kuin textillä.
