### ISSUE TITLE
Jos input-kentässä ei ole ollut arvoa, ja siihen syöttää jotain ja odottaa tarpeeksi kauan, pitäiskö toiminnallisuuksien aktivoitua?

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#5]

**Comment by nomasi** [comment]
Tästä Roban raati (tämä herätti mielenkiintoa) oli sitä mieltä että jos vaan onnistuu jotenkin kivuttomasti niin input-kentässä 1 sek viive edellisestä keyupista voisi riittää aktivoimaan sen sizeme-laskennan, mutta ei siirtämään fokusta pois kentästä.  

Usea robalainen oli sitä mieltä että kun kenttään kirjoittaa jonkun arvon niin automaattisesti nykyään jo olettaa että se lähtee tekemään jotain vaikka ei kentästä varsinaisesti poistuisikaan.  

Tän voi toteuttaa prioriteetti n:o 2 jos on hankala toteuttaa.

**Comment by tjjalava** [comment]
ei ole vaikea, tollanen ominaisuus siinä alunperin Yliniemen jäljiltä olikin. Siinä voisi myös olla sama efekti kuin sizeme.comin profiilieditorissa, jossa syötetty arvo on kursiivilla jos sitä ei ole vielä tallennettu
