### ISSUE TITLE
Mittasyöttökentän tooltip peittää kentän, jos oikealla ei ole tilaa

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#52]
@nomasi, PR:ssä #47 muutit syöttöinputkentän tooltipin alhaalta oikealle. Nyt, jos oikealla ei ole tilaa, tooltip peittää koko syöttökentän. Kokeile vaikka testisivulla http://localhost:8080/index2.html front height-kentällä. Tota pitää varmaan vielä miettiä tarkemmin (oma mielipiteeni on, ettei sitä tooltippiä tarttis koko ajan näyttää..)

**Comment by nomasi** [comment]
Joo, se alapuoli olisi paljon parempi suunta.  Mä siirsin sen oikealle kun halusin nähdä miten se overlap-kenttä vaihtuu dynaamisesti kun mittaa vaihtaa.  Se on niin hieno!  

Mut: onko iso duuni piilottaa se tooltip kun tekee ensimmäisen muutoksen siihen input-kenttään?  Siinä vaiheessa sen luulisi olevan luettu?

**Comment by tjjalava** [comment]
ei varmaan. Mutta tulisiko se sitten uudestaan näkyviin kun seuraavan kerran fokusoi kenttään?

**Comment by nomasi** [comment]
joo.  jos ei oo iso homma, niin katsotaan miten tää toimii käytännössä.

**Comment by tjjalava** [comment]
nyt tooltip häviää heti jos kenttään tulee muutoksia. Kokeilin myös sellaista, että tooltip aukeaisi aina "sisäänpäin", siis niin, että vasemmanpuoleisen kentän avaisi sen oikealle ja oikeanpuoleinen vasemmalle, mutta mun mielestä se, että tooltip peittää yhtään niitä input-kenttiä tekee käytöstä hankalaa, varsinkin kun voi olettaa, ettei keskivertoihminen kuitenkaan osaa liikkua kentästä toiseen tab-näppäimellä

**Comment by nomasi** [comment]
Tää on mun mielestä nyt ihan täydellinen.  Toimii niinkuin sen kuvittelisikin toimivan.  Hyvä!!!
