### ISSUE TITLE
Kokovalinta: Magento swatches -toiminta

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#56]
Magenton swatches -kokovalinnassa (dist/index2.html) Magento itse vaihtaa kokoa "a.swatch-link"-elementin klikkauksilla.  Meidän koodi reagoi "a":n parentin "li":n klikkauksiin, jolloin jos ja kun nämä kaksi elementtiä ei ole tismalleen päällekkäin ja samankokoisia, niin toiminta on vähän erikoista jos onnistuu klikkaamaan sitä "li"-elementtiä sieltä.  

Tälle olisi varmaan helpoin ratkaisu pakottaa CSS:llä aina elementit samankokoisiksi ja laittamalla mahdollinen swatchesin border siihen "li"-elementtiin (ei "a").

**Comment by tjjalava** [comment]
Korjaan filtteröimällä tuntemattomat tai olemattomat kokotiedot click-eventistä. Ohi-klikkauksessa ei meinaan ole mitään kokotietoa.

**Comment by tjjalava** [comment]
Korjattu: cbfbf97f03821e86f4a7a43f05e41fa1e99b80be

**Comment by nomasi** [comment]
Tää on hyvä korjaus.  Laitatko tämän korjauksen tohon live-kolmosversioon?  Tää bugi näkyy Kookengän demosaitilla (varsinkin kun kokovalintarivi menee useammalle riville), niin hienoa et tuli kuntoon!

**Comment by tjjalava** [comment]
ok. Ehkä vois olla aika julkaista eka oikea release tästä

**Comment by nomasi** [comment]
Great success!!!
