### ISSUE TITLE
Add sm_action cookie values 

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#58]
Write a cookie called "sm_action" with a value based on the current measuremental (not a word) situation.  The values are:

- **noProduct** = product has no measurements
- **noHuman** = product has measurements, no human measurements
- **hasUnsaved** = product has measurements, human measurements exist, but unsaved
- **hasProfile** = product has measurements, a SizeMe profile exists

**Comment by nomasi** [comment]
![image](https://user-images.githubusercontent.com/6150822/27576813-f7666d9c-5b26-11e7-9fab-9955e60e4fc0.png)

**Comment by nomasi** [comment]
This cookie and its value is sent to the SizeMe API with the add to cart event.  This way we can tell what SizeMe's contribution to the world has been.

**Comment by tjjalava** [comment]
mites jos käytettäisiin mieluummin sessionstoragea, joka soveltuis tällaiseen paremmin ja on helpompi käyttääkin (ei tartte mitään apukirjastoja tai helper-funktioita), ja on muutenkin "nykypäivää". Cookiena toi tieto lähetettäisiin sitä paitsi jokaisen kutsun yhteydessä kaupan palvelimelle, jonne se varsinaisesti ei kuulu.

**Comment by nomasi** [comment]
Tässä oli se juoni että serveri lähettää tän viestin.  Serveri tietää käyttäjän cookiet, mutta sessionStoragesta ei mitään. 

Ja syy miksi nimenomaan serverin pitää tää viesti lähettää, oli se että meidän pitää lähettää aika hyvät tuotetiedot jo addToCart-eventin yhteydessä ja serveri tietää ne parhaiten.

**Comment by tjjalava** [comment]
hmm, okei joo, mä luulin, että se olis käyttäjän selain. Selvä, sitten sen pitää olla cookie.. mutta samalla myös sitä suuremmalla syyllä meidän pitää joku api-key tohon keksiä, jotta voidaan varmistua siitä, että pyynnöt tulee valideista paikoista.

**Comment by nomasi** [comment]
Toisaalta noi addToCart-eventin tiedot ovat sen verran ohuet että kyllä ne pystyisi keräämään selaimen lähetettäväksi.  

Mutta; ei se poista sitä api-key-juttua, kun sitä orderComplete-eventiä ei lähetä selain millään.

**Comment by tjjalava** [comment]
no, nyt se menee cookiessa. Sellaisen huomion vielä tein, että jos käyttäjällä on monta välilehteä auki samassa kaupassa, sm_actionin arvo voi olla väärä, kun addToCartia painetaan, joten määritin cookielle pathin. Tarkoittaa sitä, että kun käyttäjä surffaa kaupassa, hänen cookie-listansa kasvaa koko ajan. Mutta sillä ei pitäisi kyllä olla mitään merkitystä.
