### ISSUE TITLE
Mittaohje-tooltip

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#6]
@nomasi:

1. Mittaohje-tooltip saa näkyä kun input-kenttä aktivoituu.   
2.  Kysymysmerkkiaktivointia ei tarvitse ollenkaan

**Comment by tjjalava** [comment]
tää on vähän ongelmallinen.. eli tooltip aktivoitaisiin inputin focus-eventillä ja piilotettaisiin blur-eventillä? Tooltipin video-linkin painaminen aiheuttaa väkisin blur-eventin inputille jolloin tooltip ja video menee piiloon. En oikein keksi robustia tapaa, jolla tooltip voisi päätellä milloin blur-eventin on tarkoitus piilottaa tooltip ja milloin ei. 

Lisäksi ainakin henkilökohtaisesti pakotetut tooltipit ärsyttää suunnattomasti.

**Comment by nomasi** [comment]
Tää ei ole mun mielestä puhtaasti pakotettu tooltip vaan enemmänkin ihan vaan käyttäjän palvelemiseksi parempi ohje että käyttäjä tietää mitä pitää tehdä.  Sitä samaa tietoa on tosi hankala saada mitenkään muuten kommunikoitua ja mä pelkään että jengi on aika laiskoja painamaan noita kysymysmerkkejä.  

Ymmärrän ton haasteen tossa eventissä, mutta mun puolesta se väkisin avattu tooltip saakin hävitä (ja focus inputista hävitä) jos video-linkkiä painetaan.  Se video on modal kuitenkin niin ei samaan aikaan mitään ole aktiivista kuitenkaan.  

Lisäksi tän tooltipin sijainti voisi olla suoraan mittakentän alla.

**Comment by tjjalava** [comment]
ei, kun se video modal ei nimenomaan aukea, koska blur-eventti hävittää sen tooltipin ennen kuin click-eventti liipaistaan. Mut mä voisin kokeilla, jos sitä blurin callbackiä vois viivyttää muutaman millisekunnin, jotta linkin click ehdittäis nappaamaan kiinni

**Comment by nomasi** [comment]
Joo, tai toinen mahis voisi olla kylmästi triggeroida se video linkin mousedownista, ei clickistä?  
https://codepen.io/mudassir0909/pen/eIHqB

**Comment by tjjalava** [comment]
joo, toi näyttää hyvältä. Mä kokeilen illemmalla
