### ISSUE TITLE
Info box on size change

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#61]
Show a info box every time SizeMe changes the size selection or fails to do so if no suitable size is found.  

Add text strings for both cases:
"We selected size %s based on your measurement.  Please check the fit."
"No fitting size was found based on your measurement."

**Comment by nomasi** [comment]
A possible place for this info box is the slider-placeholder and the info box should disappear after a delay (3 seconds) or a click on the box.

**Comment by nomasi** [comment]
When there no suitable size to be selected by SizeMe; the slider-placeholder holds the text "Select a size to see your fit" (because no suitable size could be selected).  Ideally, if we were to use this space for communication, first the info string "No fitting size..." would appear and then it would be replaced by the "Select a size..." thing.  If this too weird and/or difficult, let's think of something else.

**Comment by tjjalava** [comment]
Maybe some ui-mockups for this? First problems that come to mind is that the placeholder area is too small for longer text, unless of course we let it wrap to multiple lines.. but how's that going to look. And did you mean that the info-box would replace the placeholder text or be placed over/under the text? And what kind of info box? Like [Bootstrap's alerts](https://v4-alpha.getbootstrap.com/components/alerts/) or something else?

**Comment by nomasi** [comment]
Yeah, these are good questions.  I'll consult Jaakko asap and get back with mockups.  It's possible that we don't show a text box for success; only change the placeholder text to "No fitting size..." on failure.

**Comment by nomasi** [comment]
Text-wrapping in the placeholder is a very bad option, but I wouldn't want to add new UI elements just for this.

**Comment by nomasi** [comment]
The plan is to use the placeholder as a text space for both situations ("selected size X" and "couldn't find a size").  

1)  If there is no fitting size, replace the placeholder text with "No size was found based on your measurement".  This placeholder text can remain until it's replaced by something else.  

![image](https://user-images.githubusercontent.com/6150822/29062811-dc958e3c-7c2b-11e7-9029-980109bf0f1f.png)

2)  If we are able to select a size, replace the placeholder text with "We selected size %s for you".  This text (the placeholder) should fade away by itself after 2 seconds (or after a click on the placeholder area, whichever comes first).  

![image](https://user-images.githubusercontent.com/6150822/29063315-eae13f34-7c2d-11e7-97ff-2f86f6a09431.png)

**Comment by nomasi** [comment]
Hey, the idea for the "We selected size xx for you" message was for it to appear when SizeMe changes the size selection.  Now it appears on every size change (spawning from the matchState == "match") even when the user changes the size,  Would it be difficult to have this only appear on SizeMe's size change (-> match)?

**Comment by tjjalava** [comment]
oh, that was not supposed to work like that.. I'll check it later
