### ISSUE TITLE
The No-fit situation should rise product-specifically

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#65]
![image](https://user-images.githubusercontent.com/6150822/29062253-a679aca4-7c29-11e7-828b-e8686eda14a3.png)

If the user has measurements, but no measurements for the current product, the matchState status should be "no-fit" and the placeholder text should be fine.  

This bug won't appear in Kookenkä, because these other fields (chest, frontHeight) can't have values in their environment.

**Comment by tjjalava** [comment]
This should be fixed already. If user's match's accuracy is 0 (none of the product's measurements exist in the user's measurements), match status is always "no-fit"
