### ISSUE TITLE
Small conversion bug in getSizeName function

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#67]
![image](https://user-images.githubusercontent.com/6150822/29421465-d6baad7c-837d-11e7-88ad-c89a92bdf98e.png)

Surprisingly, the size names might even have forward slashes in them!

**Comment by nomasi** [comment]
http://test-kookenka-prod.igence.fi/naisten-mallisto/avokkaat-ja-juhlakengat/ho-3-128000-2721.html

**Comment by tjjalava** [comment]
Reason: https://www.i18next.com/interpolation.html#unescape
