### ISSUE TITLE
GA events missing altogether on some sites

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#70]
Check:

https://www.sizemedemo.com/magento19/t-shirt.html?___store=default

This page won't send out any GA events although there are no visible js errors (as in other store fronts).  The analytics.js is loaded, but no collect requests seem to be leaving.  Tested on Firefox and Chrome.  

Could the reason be related to https vs http?  All the test pages running plain http are working (localhost, test-kookenka), but at least this https one is not with no other differences that I can think of.

**Comment by tjjalava** [comment]
That seemed to fix the issue.
