### ISSUE TITLE
Most different add to cart event types don't work

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#71]
There's something off with the code: index.js:43 onwards.

    const fn = () => {
        const { loggedIn, sizemeProductPage } = sizemeStore.getState();
        if (loggedIn && sizemeProductPage) {
            trackEvent("addToCartSM", "Store: Product added to cart by SizeMe user");
        } else if (loggedIn && !sizemeProductPage) {
            trackEvent("addNonSMToCartSM", "Store: Non-SizeMe product added to cart by SizeMe user");
        } else if (!loggedIn && sizemeProductPage) {
            trackEvent("addToCart", "Store: Product added to cart");
        } else {
            trackEvent("addNonSMToCart", "Store: Non-SizeMe product added to cart");
        }
    };

Only the addNonSMToCart event is actually ever fired.

**Comment by nomasi** [comment]
If the fix for this is really complicated, we could reduce this to simply addToCart for all products.  We get the SizeMe contribution via the webstore plugin.

**Comment by tjjalava** [comment]
WTF? Who forgot to copy the properties when that code was moved to index.js.. 🤦‍♂️
