### ISSUE TITLE
Set default values for sizeme_options

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#74]
At least these:
- debugState: false
- gaTrackingId: UA-40735596-1

**Comment by tjjalava** [comment]
debugState yes, but I haven't put a default value for gaTrackingId because someone will forget to set it in testing or development environments and create bogus events for the real account. They can be filtered away, of course, so maybe that's not a problem?

**Comment by nomasi** [comment]
Yeah, it might actually be the right idea to always set the GA tracking id according to debugState.  

If debugState is true, use UA-40735596-2, otherwise use UA-40735596-1 always?

Then we would always have the possibility to follow the events of SizeMe sites.

**Comment by nomasi** [comment]
I can't think of a situation where we would want a client to use their own GA account for these...

**Comment by tjjalava** [comment]
We may need to temporarely enable debug output in customer's site to debug possible problems, so enforced trackingId will fail there.. but that should be only for a short periods so maybe that's not a big deal.. and yeah, customer shouldn't be able to set any other tracking id's than ours

**Comment by nomasi** [comment]
Yeah, we can live with that scenario.

**Comment by tjjalava** [comment]
Can you check with debugState false/true at sizemedemo before making a release

**Comment by nomasi** [comment]
Nothing coming out with sizeme_options.debugState = true; ?

https://www.sizemedemo.com/magento19/t-shirt.html

**Comment by nomasi** [comment]
Wait, it's probably fine.

**Comment by nomasi** [comment]
It's good.
