### ISSUE TITLE
The vertical alignment of the overlap text fails in Safari

### ISSUE THREAD

**Issue by nomasi** [BA-Group/sizeme-react#77]
![nayttokuva 2017-07-04 kello 12 25 56](https://user-images.githubusercontent.com/6150822/30415072-04748244-992f-11e7-9b6e-0dec03459883.png)

Screenshot from a slightly older version of the UI, but the problem is supposedly still there.  I don't have Safari myself, so it's hard to test.  (browsershots et al are not good with dynamic stuff)

**Comment by nomasi** [comment]
The fix attempt didn't do the trick.

**Comment by nomasi** [comment]
@tjjalava did you have access to a Safari (browser)?

**Comment by tjjalava** [comment]
yeah, doesn't work

**Comment by tjjalava** [comment]
Works for me now

**Comment by nomasi** [comment]
Great!  I'll ask the reporter (Jaakko) to confirm and I can do a release tomorrow.

**Comment by nomasi** [comment]
Fix Confirmed!  Good!
