### ISSUE TITLE
Overlap-kuvan pinch-kuva vähän epäselvä, katotaan kaikki läpi

### ISSUE THREAD

**Issue by tjjalava** [BA-Group/sizeme-react#9]

**Comment by nomasi** [comment]
1. Lisätään kaikkien viivojen paksuuksia +50%
2. Alarajaus ei skulaa (kts. seuraava kommentti)
3. Pinch-kuvan vaate valkoiseksi
4. Lisätään napa front height -kuvaan.

**Comment by nomasi** [comment]
2.  tää korjaantui kun laitoin:
.overlap-box .overlap-svg svg { display: block; }

**Comment by tjjalava** [comment]
tekeekö joku noi muutokset jollain oikealla svg-editorilla? Mä oon lähinnä muokannut viewboxia ja piirrelly parit viivat käsin, mutta noin isot muutokset alkaa olemaan jo vähän liikaa sillä tekniikalla. Toisaalta.. editointien pohjaksi voisi ottaa ne muokkaamani kuvat, jottei niitä muokkauksia tartte tehdä uudestaan..

**Comment by nomasi** [comment]
Jaakko pystyy editoimaan noita suoraan.  Sinne voisi olla hyvä irroittaa niistä nyt ainakin väri ja ne kaksi (?) viivanpaksuutta ulos muuttujiksi (props.lineColor, props.lineWidth1, props.lineWidth2 jne), niin helpompi tehdä versioita.  Niihin tulee kyllä nopeasti tarve tehdä kauppakohtaisia muutoksia, mutta niihin voidaan kyllä tollakin menetelmällä keksiä jotain.  

Esim. Magentossa, kaupan adminin määrittämä sizeme-lisäluokka ("skin") voidaan kirjoittaa myös UI.Optionsiin ja silloin se on myös koodissa tän svg:n käytettävissä, eikös juu?

**Comment by nomasi** [comment]
Jaakko tekee ehdotuksen tosta pinch-kuvan korvaajasta.

**Comment by nomasi** [comment]
Tehdään kuitenkin muuttujiksi noi viivapaksuudet ja värit.  Ja muutkin noi ekan kommentin 4 kohtaa.

**Comment by tjjalava** [comment]
nää oli vissiin jo tehty?

**Comment by nomasi** [comment]
Joo, tärkein tästä on hoidettu.  Chest-kuvasta on Jaakolta hyvä ehdotus, mutta tehdään joskus myöhemmin.
